# Generated by Django 3.0.6 on 2020-06-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortation', models.CharField(max_length=50)),
                ('branch_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('store_address', models.CharField(max_length=200)),
                ('operating_time', models.CharField(max_length=100)),
                ('location_url', models.URLField(max_length=2000)),
            ],
            options={
                'db_table': 'stores',
            },
        ),
    ]
