# Generated by Django 3.0.6 on 2020-06-23 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_spec', models.CharField(max_length=50)),
                ('counseling_info', models.CharField(max_length=500)),
                ('return_policy', models.CharField(max_length=2000)),
                ('expiration_date', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('quality_assurance', models.CharField(max_length=200)),
                ('vendor', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'basicinformation',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color_url', models.URLField(max_length=2000, null=True)),
                ('ingredient_info', models.CharField(max_length=2000, null=True)),
                ('stock_quantity', models.IntegerField(default=1000)),
            ],
            options={
                'db_table': 'colors',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'manufacturers',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('simple_description', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usage', models.CharField(max_length=50)),
                ('kfda_audit', models.CharField(max_length=100)),
                ('caution', models.CharField(max_length=1000)),
                ('is_soldout', models.BooleanField(default=False)),
                ('outer_back_image_url', models.URLField(max_length=2000, null=True)),
                ('outer_front_image_url', models.URLField(max_length=2000, null=True)),
                ('inner_image_url', models.URLField(max_length=2000, null=True)),
                ('basic_information', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.BasicInformation')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Color')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Manufacturer')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Category')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product')),
            ],
            options={
                'db_table': 'categories_products',
            },
        ),
    ]
